"""Static S&P 500 membership by GICS sector, mapped to the Select Sector SPDRs.

Snapshot of full S&P 500 membership by GICS sector, taken mid-2026.

This is a snapshot, not a live feed. Index membership drifts: names get added,
dropped, acquired, or reclassified between GICS sectors. Re-check before
treating any single name as authoritative.
"""

SECTOR_NAMES = {
    "XLK": "Information Technology",
    "XLV": "Health Care",
    "XLF": "Financials",
    "XLY": "Consumer Discretionary",
    "XLC": "Communication Services",
    "XLI": "Industrials",
    "XLP": "Consumer Staples",
    "XLE": "Energy",
    "XLU": "Utilities",
    "XLRE": "Real Estate",
    "XLB": "Materials",
}

CONSTITUENTS = {
"XLK": [
 ("NVDA","NVIDIA"),("MSFT","Microsoft"),("AAPL","Apple"),("AVGO","Broadcom"),
 ("AMD","Advanced Micro Devices"),("CRM","Salesforce"),("ORCL","Oracle"),("ADBE","Adobe"),
 ("ACN","Accenture"),("CSCO","Cisco Systems"),("TXN","Texas Instruments"),("QCOM","Qualcomm"),
 ("INTU","Intuit"),("IBM","IBM"),("AMAT","Applied Materials"),("NOW","ServiceNow"),
 ("MU","Micron Technology"),("LRCX","Lam Research"),("ADI","Analog Devices"),("KLAC","KLA Corp"),
 ("PANW","Palo Alto Networks"),("SNPS","Synopsys"),("CDNS","Cadence Design"),("INTC","Intel"),
 ("ANET","Arista Networks"),("MSI","Motorola Solutions"),("ROP","Roper Technologies"),
 ("APH","Amphenol"),("NXPI","NXP Semiconductors"),("FTNT","Fortinet"),("MCHP","Microchip"),
 ("ON","ON Semiconductor"),("GLW","Corning"),("HPQ","HP Inc"),("DELL","Dell Technologies"),
 ("WDC","Western Digital"),("STX","Seagate"),("TER","Teradyne"),("SWKS","Skyworks"),
 ("KEYS","Keysight"),("CDW","CDW Corp"),("IT","Gartner"),
 ("TYL","Tyler Technologies"),("ZBRA","Zebra Technologies"),("JBL","Jabil"),
 ("HPE","HP Enterprise"),("NTAP","NetApp"),("TDY","Teledyne"),("PTC","PTC Inc"),
 ("FSLR","First Solar"),
 ("APP","AppLovin"),("PLTR","Palantir"),("CRWD","CrowdStrike"),("WDAY","Workday"),
 ("ADSK","Autodesk"),("GDDY","GoDaddy"),("VRSN","VeriSign"),("AKAM","Akamai"),
 ("FFIV","F5 Inc"),("EPAM","EPAM Systems"),("GEN","Gen Digital"),
 ("SMCI","Super Micro Computer"),("TRMB","Trimble"),("CTSH","Cognizant"),
 ("MPWR","Monolithic Power"),("ENPH","Enphase Energy"),("TEL","TE Connectivity"),
 ("FICO","Fair Isaac"),("PAYC","Paycom"),("DAY","Dayforce"),
],
"XLV": [
 ("LLY","Eli Lilly"),("UNH","UnitedHealth"),("JNJ","Johnson & Johnson"),("ABBV","AbbVie"),
 ("MRK","Merck"),("TMO","Thermo Fisher"),("ABT","Abbott Labs"),("ISRG","Intuitive Surgical"),
 ("AMGN","Amgen"),("DHR","Danaher"),("PFE","Pfizer"),("BSX","Boston Scientific"),
 ("VRTX","Vertex Pharmaceuticals"),("SYK","Stryker"),("BMY","Bristol-Myers Squibb"),
 ("GILD","Gilead Sciences"),("MDT","Medtronic"),("CI","Cigna"),("ELV","Elevance Health"),
 ("REGN","Regeneron"),("MCK","McKesson"),("CVS","CVS Health"),("ZTS","Zoetis"),
 ("BDX","Becton Dickinson"),("HCA","HCA Healthcare"),("EW","Edwards Lifesciences"),
 ("A","Agilent"),("IQV","IQVIA"),("IDXX","IDEXX Labs"),("GEHC","GE HealthCare"),
 ("CNC","Centene"),("MRNA","Moderna"),("DXCM","DexCom"),("RMD","ResMed"),
 ("WST","West Pharmaceutical"),("BIIB","Biogen"),("COR","Cencora"),("ZBH","Zimmer Biomet"),
 ("MTD","Mettler-Toledo"),("BAX","Baxter"),("HOLX","Hologic"),("VTRS","Viatris"),
 ("LH","Labcorp"),("DGX","Quest Diagnostics"),("STE","Steris"),("PODD","Insulet"),
 ("MOH","Molina Healthcare"),("CAH","Cardinal Health"),("CRL","Charles River Labs"),
 ("HUM","Humana"),("WAT","Waters"),("COO","Cooper Companies"),("ILMN","Illumina"),
 ("ALGN","Align Technology"),("DVA","DaVita"),("UHS","Universal Health Services"),
 ("HSIC","Henry Schein"),("INCY","Incyte"),("TECH","Bio-Techne"),("RVTY","Revvity"),
 ("SOLV","Solventum"),("XRAY","Dentsply Sirona"),("BIO","Bio-Rad Labs"),
],
"XLF": [
 ("BRK-B","Berkshire Hathaway"),("JPM","JPMorgan Chase"),("V","Visa"),("MA","Mastercard"),
 ("BAC","Bank of America"),("WFC","Wells Fargo"),("GS","Goldman Sachs"),("MS","Morgan Stanley"),
 ("SPGI","S&P Global"),("AXP","American Express"),("BLK","BlackRock"),("C","Citigroup"),
 ("PGR","Progressive"),("SCHW","Charles Schwab"),("CB","Chubb"),("MMC","Marsh & McLennan"),
 ("BX","Blackstone"),("FI","Fiserv"),("ICE","Intercontinental Exchange"),("CME","CME Group"),
 ("PYPL","PayPal"),("AON","Aon"),("USB","U.S. Bancorp"),("PNC","PNC Financial"),
 ("COF","Capital One"),("TFC","Truist Financial"),("AJG","Arthur J. Gallagher"),
 ("AIG","American International Group"),("MET","MetLife"),("TRV","Travelers"),("AFL","Aflac"),
 ("ALL","Allstate"),("PRU","Prudential Financial"),("BK","BNY Mellon"),("AMP","Ameriprise"),
 ("DFS","Discover Financial"),("MSCI","MSCI Inc"),("NDAQ","Nasdaq Inc"),("STT","State Street"),
 ("HIG","Hartford Financial"),("WTW","Willis Towers Watson"),("TROW","T. Rowe Price"),
 ("RJF","Raymond James"),("FITB","Fifth Third Bancorp"),("MTB","M&T Bank"),
 ("CINF","Cincinnati Financial"),("HBAN","Huntington Bancshares"),("RF","Regions Financial"),
 ("CFG","Citizens Financial"),("KEY","KeyCorp"),
 ("KKR","KKR & Co"),("APO","Apollo Global"),("ARES","Ares Management"),("MCO","Moody's"),
 ("FIS","Fidelity National Info"),("GPN","Global Payments"),("CPAY","Corpay"),
 ("JKHY","Jack Henry"),("COIN","Coinbase"),("BRO","Brown & Brown"),("ACGL","Arch Capital"),
 ("EG","Everest Group"),("GL","Globe Life"),("L","Loews"),("PFG","Principal Financial"),
 ("IVZ","Invesco"),("BEN","Franklin Resources"),("NTRS","Northern Trust"),
 ("SYF","Synchrony Financial"),("WRB","W.R. Berkley"),("AIZ","Assurant"),
 ("ERIE","Erie Indemnity"),("CBOE","Cboe Global Markets"),("MKTX","MarketAxess"),
 ("FDS","FactSet"),
],
"XLY": [
 ("AMZN","Amazon"),("TSLA","Tesla"),("HD","Home Depot"),("MCD","McDonald's"),
 ("BKNG","Booking Holdings"),("LOW","Lowe's"),("TJX","TJX Companies"),("SBUX","Starbucks"),
 ("NKE","Nike"),("ORLY","O'Reilly Automotive"),("CMG","Chipotle"),("ABNB","Airbnb"),
 ("MAR","Marriott"),("GM","General Motors"),("HLT","Hilton"),("AZO","AutoZone"),
 ("F","Ford Motor"),("ROST","Ross Stores"),("DHI","D.R. Horton"),("LEN","Lennar"),
 ("YUM","Yum! Brands"),("RCL","Royal Caribbean"),("EBAY","eBay"),("LVS","Las Vegas Sands"),
 ("TSCO","Tractor Supply"),("NVR","NVR Inc"),("PHM","PulteGroup"),("DECK","Deckers Outdoor"),
 ("EXPE","Expedia"),("CCL","Carnival"),("DRI","Darden Restaurants"),("ULTA","Ulta Beauty"),
 ("GRMN","Garmin"),("APTV","Aptiv"),("BBY","Best Buy"),("KMX","CarMax"),("POOL","Pool Corp"),
 ("WYNN","Wynn Resorts"),("MGM","MGM Resorts"),("LKQ","LKQ Corp"),
 ("NCLH","Norwegian Cruise Line"),("CZR","Caesars Entertainment"),("RL","Ralph Lauren"),
 ("TPR","Tapestry"),
 ("DASH","DoorDash"),("DPZ","Domino's Pizza"),("LULU","Lululemon"),("GPC","Genuine Parts"),
 ("WSM","Williams-Sonoma"),("HAS","Hasbro"),("MHK","Mohawk Industries"),
 ("BLDR","Builders FirstSource"),
],
"XLC": [
 ("META","Meta Platforms"),("GOOGL","Alphabet A"),("GOOG","Alphabet C"),("NFLX","Netflix"),
 ("DIS","Walt Disney"),("TMUS","T-Mobile US"),("CMCSA","Comcast"),("VZ","Verizon"),
 ("T","AT&T"),("CHTR","Charter Communications"),("EA","Electronic Arts"),
 ("TTWO","Take-Two Interactive"),("OMC","Omnicom"),("LYV","Live Nation"),
 ("WBD","Warner Bros. Discovery"),("IPG","Interpublic"),("NWSA","News Corp A"),
 ("FOXA","Fox Corp A"),("MTCH","Match Group"),
 ("NWS","News Corp B"),("FOX","Fox Corp B"),
],
"XLI": [
 ("GE","GE Aerospace"),("CAT","Caterpillar"),("RTX","RTX Corp"),("UNP","Union Pacific"),
 ("HON","Honeywell"),("BA","Boeing"),("ETN","Eaton"),("LMT","Lockheed Martin"),
 ("DE","Deere & Co"),("UPS","United Parcel Service"),("ADP","Automatic Data Processing"),
 ("TT","Trane Technologies"),("PH","Parker Hannifin"),("GD","General Dynamics"),
 ("ITW","Illinois Tool Works"),("MMM","3M"),("EMR","Emerson Electric"),
 ("NOC","Northrop Grumman"),("CSX","CSX Corp"),("FDX","FedEx"),("NSC","Norfolk Southern"),
 ("WM","Waste Management"),("CTAS","Cintas"),("CARR","Carrier Global"),("PCAR","PACCAR"),
 ("JCI","Johnson Controls"),("GEV","GE Vernova"),("CMI","Cummins"),("PWR","Quanta Services"),
 ("URI","United Rentals"),("PAYX","Paychex"),("AME","Ametek"),("OTIS","Otis Worldwide"),
 ("RSG","Republic Services"),("FAST","Fastenal"),("LHX","L3Harris"),("VRSK","Verisk"),
 ("IR","Ingersoll Rand"),("EFX","Equifax"),("DAL","Delta Air Lines"),
 ("ODFL","Old Dominion Freight"),("HWM","Howmet Aerospace"),("AXON","Axon Enterprise"),
 ("XYL","Xylem"),("UAL","United Airlines"),("LUV","Southwest Airlines"),("DOV","Dover"),
 ("ROK","Rockwell Automation"),("WAB","Wabtec"),("BR","Broadridge"),
 ("CPRT","Copart"),("TDG","TransDigm"),("VLTO","Veralto"),("EME","EMCOR Group"),
 ("J","Jacobs Solutions"),("MAS","Masco"),("SNA","Snap-on"),
 ("SWK","Stanley Black & Decker"),("ALLE","Allegion"),("NDSN","Nordson"),
 ("IEX","IDEX Corp"),("GNRC","Generac"),("PNR","Pentair"),("CHRW","C.H. Robinson"),
 ("EXPD","Expeditors Intl"),("JBHT","J.B. Hunt"),("TXT","Textron"),
 ("HII","Huntington Ingalls"),("LDOS","Leidos"),("BAH","Booz Allen Hamilton"),
 ("ROL","Rollins"),("FTV","Fortive"),("AOS","A.O. Smith"),("GWW","W.W. Grainger"),
],
"XLP": [
 ("COST","Costco"),("WMT","Walmart"),("PG","Procter & Gamble"),("KO","Coca-Cola"),
 ("PEP","PepsiCo"),("PM","Philip Morris Intl"),("MO","Altria"),("MDLZ","Mondelez"),
 ("CL","Colgate-Palmolive"),("TGT","Target"),("KMB","Kimberly-Clark"),
 ("STZ","Constellation Brands"),("GIS","General Mills"),("SYY","Sysco"),("KVUE","Kenvue"),
 ("KDP","Keurig Dr Pepper"),("HSY","Hershey"),("KR","Kroger"),("ADM","Archer-Daniels-Midland"),
 ("MNST","Monster Beverage"),("DG","Dollar General"),("DLTR","Dollar Tree"),
 ("EL","Estee Lauder"),("CHD","Church & Dwight"),("MKC","McCormick"),("K","Kellanova"),
 ("CAG","Conagra Brands"),("TSN","Tyson Foods"),("HRL","Hormel Foods"),("SJM","J.M. Smucker"),
 ("CPB","Campbell's"),("LW","Lamb Weston"),("BG","Bunge Global"),("TAP","Molson Coors"),
 ("CLX","Clorox"),("BF-B","Brown-Forman B"),
 ("KHC","Kraft Heinz"),
],
"XLE": [
 ("XOM","Exxon Mobil"),("CVX","Chevron"),("COP","ConocoPhillips"),("EOG","EOG Resources"),
 ("WMB","Williams Companies"),("SLB","SLB"),("OKE","ONEOK"),("PSX","Phillips 66"),
 ("MPC","Marathon Petroleum"),("KMI","Kinder Morgan"),("VLO","Valero Energy"),
 ("OXY","Occidental Petroleum"),("BKR","Baker Hughes"),("HAL","Halliburton"),
 ("DVN","Devon Energy"),("FANG","Diamondback Energy"),("TRGP","Targa Resources"),
 ("CTRA","Coterra Energy"),("EQT","EQT Corp"),("APA","APA Corp"),("EXE","Expand Energy"),
],
"XLU": [
 ("NEE","NextEra Energy"),("SO","Southern Company"),("DUK","Duke Energy"),
 ("CEG","Constellation Energy"),("AEP","American Electric Power"),("SRE","Sempra"),
 ("D","Dominion Energy"),("PCG","PG&E Corp"),("EXC","Exelon"),("XEL","Xcel Energy"),
 ("ED","Consolidated Edison"),("PEG","Public Service Enterprise"),("VST","Vistra"),
 ("WEC","WEC Energy"),("EIX","Edison International"),("AWK","American Water Works"),
 ("DTE","DTE Energy"),("ETR","Entergy"),("AEE","Ameren"),("PPL","PPL Corp"),
 ("FE","FirstEnergy"),("CMS","CMS Energy"),("CNP","CenterPoint Energy"),("ATO","Atmos Energy"),
 ("NRG","NRG Energy"),("LNT","Alliant Energy"),("EVRG","Evergy"),("NI","NiSource"),
 ("ES","Eversource Energy"),("AES","AES Corp"),("PNW","Pinnacle West"),
],
"XLRE": [
 ("PLD","Prologis"),("AMT","American Tower"),("EQIX","Equinix"),("WELL","Welltower"),
 ("SPG","Simon Property"),("PSA","Public Storage"),("O","Realty Income"),
 ("DLR","Digital Realty"),("CCI","Crown Castle"),("CBRE","CBRE Group"),
 ("EXR","Extra Space Storage"),("VICI","VICI Properties"),("AVB","AvalonBay"),
 ("IRM","Iron Mountain"),("EQR","Equity Residential"),("SBAC","SBA Communications"),
 ("WY","Weyerhaeuser"),("INVH","Invitation Homes"),("MAA","Mid-America Apartment"),
 ("ESS","Essex Property"),("ARE","Alexandria Real Estate"),("DOC","Healthpeak"),
 ("KIM","Kimco Realty"),("UDR","UDR Inc"),("HST","Host Hotels"),("REG","Regency Centers"),
 ("CPT","Camden Property"),("BXP","BXP Inc"),("FRT","Federal Realty"),
 ("VTR","Ventas"),("CSGP","CoStar Group"),
],
"XLB": [
 ("LIN","Linde"),("SHW","Sherwin-Williams"),("APD","Air Products"),("ECL","Ecolab"),
 ("FCX","Freeport-McMoRan"),("NEM","Newmont"),("NUE","Nucor"),("DOW","Dow Inc"),
 ("DD","DuPont"),("PPG","PPG Industries"),("LYB","LyondellBasell"),("VMC","Vulcan Materials"),
 ("MLM","Martin Marietta"),("IFF","Intl Flavors & Fragrances"),("PKG","Packaging Corp"),
 ("AMCR","Amcor"),("STLD","Steel Dynamics"),("CF","CF Industries"),("BALL","Ball Corp"),
 ("IP","International Paper"),("ALB","Albemarle"),("EMN","Eastman Chemical"),
 ("CE","Celanese"),("MOS","Mosaic"),
 ("SW","Smurfit Westrock"),("AVY","Avery Dennison"),
],
}

TICKER_TO_ETF = {t: etf for etf, rows in CONSTITUENTS.items() for t, _ in rows}
TICKER_TO_NAME = {t: n for rows in CONSTITUENTS.values() for t, n in rows}


# ─────────────────────────────────────────────────────────────────────────────
# Sub-sector and thematic ETFs, mapped to the sector SPDR they sit inside.
# ticker -> (parent SPDR, description)
# ─────────────────────────────────────────────────────────────────────────────
SUBSECTOR_ETFS = {
    "SOXX": ("XLK", "Semiconductors · Broad"),
    "SMH": ("XLK", "Semiconductors · Broad"),
    "XSD": ("XLK", "Semiconductors · Equal-weight"),
    "PSI": ("XLK", "Semiconductors · Broad"),
    "DRAM": ("XLK", "Semiconductors · Memory / storage"),
    "IGV": ("XLK", "Software · Broad software"),
    "SKYY": ("XLK", "Software · Cloud computing"),
    "WCLD": ("XLK", "Software · Cloud / SaaS"),
    "CIBR": ("XLK", "Software · Cybersecurity"),
    "HACK": ("XLK", "Software · Cybersecurity"),
    "BUG": ("XLK", "Software · Cybersecurity"),
    "FDN": ("XLK", "Internet · Broad internet"),
    "AIQ": ("XLK", "AI & Data · AI / big data"),
    "BOTZ": ("XLK", "AI & Data · Robotics & automation"),
    "ROBO": ("XLK", "AI & Data · Robotics"),
    "ARKQ": ("XLK", "AI & Data · Robotics"),
    "QTUM": ("XLK", "Quantum · Quantum computing"),
    "FNGS": ("XLK", "Mega-cap tech · FANG+"),
    "MAGS": ("XLK", "Mega-cap tech · Magnificent 7"),
    "MGK": ("XLK", "Mega-cap tech · Mega-cap growth"),
    "IYZ": ("XLC", "Telecom"),
    "ESPO": ("XLC", "Media & Entertainment · Video games / esports"),
    "HERO": ("XLC", "Media & Entertainment · Video games / esports"),
    "SOCL": ("XLC", "Media & Entertainment · Social media"),
    "KBWB": ("XLF", "Banks · Money-center / big banks"),
    "KBE": ("XLF", "Banks · Broad banks"),
    "KRE": ("XLF", "Banks · Regional banks"),
    "IAT": ("XLF", "Banks · Regional banks"),
    "KBWR": ("XLF", "Banks · Regional banks"),
    "IAI": ("XLF", "Capital Markets · Brokers & exchanges"),
    "KIE": ("XLF", "Insurance"),
    "IAK": ("XLF", "Insurance"),
    "IPAY": ("XLF", "Fintech · Payments & fintech"),
    "FINX": ("XLF", "Fintech · Payments & fintech"),
    "ARKF": ("XLF", "Fintech · Payments & fintech"),
    "BLOK": ("XLF", "Crypto financials · Blockchain & miners"),
    "WGMI": ("XLF", "Crypto financials · Blockchain & miners"),
    "DAPP": ("XLF", "Crypto financials · Blockchain & miners"),
    "XBI": ("XLV", "Biotech · Equal-weight biotech"),
    "IBB": ("XLV", "Biotech · Cap-weighted biotech"),
    "XPH": ("XLV", "Pharmaceuticals · Equal-weight pharma"),
    "PPH": ("XLV", "Pharmaceuticals · Large-cap pharma"),
    "IHI": ("XLV", "Medical Devices"),
    "XHE": ("XLV", "Medical Devices"),
    "IHF": ("XLV", "Providers & Services"),
    "XHS": ("XLV", "Providers & Services"),
    "ARKG": ("XLV", "Genomics"),
    "GNOM": ("XLV", "Genomics"),
    "IDNA": ("XLV", "Genomics"),
    "MSOS": ("XLV", "Cannabis · U.S. MSOs"),
    "XOP": ("XLE", "Exploration & Production · Equal-weight E&P"),
    "IEO": ("XLE", "Exploration & Production · Cap-weighted E&P"),
    "OIH": ("XLE", "Oil Services"),
    "XES": ("XLE", "Oil Services"),
    "CRAK": ("XLE", "Refiners"),
    "AMLP": ("XLE", "Midstream / MLP"),
    "MLPA": ("XLE", "Midstream / MLP"),
    "MLPX": ("XLE", "Midstream / MLP"),
    "FCG": ("XLE", "Natural Gas · Equities"),
    "URA": ("XLE", "Uranium & Nuclear · Uranium miners"),
    "URNM": ("XLE", "Uranium & Nuclear · Uranium miners"),
    "NLR": ("XLE", "Uranium & Nuclear · Nuclear value chain"),
    "NUKZ": ("XLE", "Uranium & Nuclear · Nuclear value chain"),
    "TAN": ("XLE", "Clean Energy · Solar"),
    "ICLN": ("XLE", "Clean Energy · Broad clean energy"),
    "QCLN": ("XLE", "Clean Energy · Broad clean energy"),
    "PBW": ("XLE", "Clean Energy · Broad clean energy"),
    "FAN": ("XLE", "Clean Energy · Wind"),
    "ITA": ("XLI", "Aerospace & Defense · Cap-weighted"),
    "XAR": ("XLI", "Aerospace & Defense · Equal-weight"),
    "PPA": ("XLI", "Aerospace & Defense"),
    "UFO": ("XLI", "Space · Pure space"),
    "ARKX": ("XLI", "Space · Pure space"),
    "XTN": ("XLI", "Transportation · Equal-weight"),
    "IYT": ("XLI", "Transportation · Cap-weighted"),
    "JETS": ("XLI", "Transportation · Airlines"),
    "AWAY": ("XLI", "Travel & Leisure · Travel"),
    "CRUZ": ("XLI", "Travel & Leisure · Travel"),
    "PAVE": ("XLI", "Infrastructure · U.S. infrastructure"),
    "IFRA": ("XLI", "Infrastructure · Global"),
    "IGF": ("XLI", "Infrastructure · Global"),
    "MOO": ("XLI", "Machinery & Agribusiness"),
    "EVX": ("XLI", "Waste & Environmental"),
    "XME": ("XLB", "Metals & Mining · Broad"),
    "GDX": ("XLB", "Metals & Mining · Gold miners"),
    "GDXJ": ("XLB", "Metals & Mining · Junior gold miners"),
    "SIL": ("XLB", "Metals & Mining · Silver miners"),
    "SILJ": ("XLB", "Metals & Mining · Silver miners"),
    "COPX": ("XLB", "Metals & Mining · Copper miners"),
    "SLX": ("XLB", "Metals & Mining · Steel"),
    "LIT": ("XLB", "Metals & Mining · Lithium & battery"),
    "BATT": ("XLB", "Metals & Mining · Lithium & battery"),
    "REMX": ("XLB", "Metals & Mining · Rare earth / strategic"),
    "CRIT": ("XLB", "Metals & Mining · Rare earth / strategic"),
    "WOOD": ("XLB", "Paper & Timber"),
    "CUT": ("XLB", "Paper & Timber"),
    "XRT": ("XLY", "Retail · Equal-weight retail"),
    "RTH": ("XLY", "Retail · Cap-weighted"),
    "ONLN": ("XLY", "Retail · E-commerce"),
    "IBUY": ("XLY", "Retail · E-commerce"),
    "EBIZ": ("XLY", "Retail · E-commerce"),
    "ITB": ("XLY", "Homebuilders · Home construction"),
    "XHB": ("XLY", "Homebuilders · Building products"),
    "PKB": ("XLY", "Homebuilders · Building products"),
    "CARZ": ("XLY", "Autos & EV"),
    "DRIV": ("XLY", "Autos & EV"),
    "IDRV": ("XLY", "Autos & EV"),
    "BJK": ("XLY", "Gaming & Casinos"),
    "BETZ": ("XLY", "Gaming & Casinos"),
    "EATZ": ("XLY", "Restaurants"),
    "MENU": ("XLY", "Restaurants"),
    "PEJ": ("XLY", "Leisure & Travel"),
    "PBJ": ("XLP", "Food & Beverage"),
    "FTXG": ("XLP", "Food & Beverage"),
    "VEGI": ("XLP", "Agriculture"),
    "PHO": ("XLU", "Water"),
    "FIW": ("XLU", "Water"),
    "CGW": ("XLU", "Water"),
    "REM": ("XLRE", "Mortgage REITs"),
    "MORT": ("XLRE", "Mortgage REITs"),
    "SRVR": ("XLRE", "Specialty REITs · Data centers & infrastructure"),
    "DTCR": ("XLRE", "Specialty REITs · Data centers & infrastructure"),
    "INDS": ("XLRE", "Specialty REITs · Industrial"),
    "REZ": ("XLRE", "Specialty REITs · Residential"),
}

SUBSECTOR_PARENT = {t: v[0] for t, v in SUBSECTOR_ETFS.items()}
SUBSECTOR_LABEL = {t: v[1] for t, v in SUBSECTOR_ETFS.items()}
