"""Static S&P 500 membership by GICS sector, mapped to the Select Sector SPDRs.

Snapshot taken mid-2026 and deliberately weighted toward the larger, liquid
names in each sector rather than the full 500 - the small tail adds noise to a
relative-value screen without adding much information.

This is a snapshot, not a live feed. Index membership drifts: names get added,
dropped, acquired, or reclassified between GICS sectors. Re-check before
treating any single name as authoritative.
"""

SECTOR_NAMES = {
    "XLK": "Information Technology",
    "XLV": "Health Care",
    "XLF": "Financials",
    "XLY": "Consumer Discretionary",
    "XLC": "Communication Services",
    "XLI": "Industrials",
    "XLP": "Consumer Staples",
    "XLE": "Energy",
    "XLU": "Utilities",
    "XLRE": "Real Estate",
    "XLB": "Materials",
}

CONSTITUENTS = {
"XLK": [
 ("NVDA","NVIDIA"),("MSFT","Microsoft"),("AAPL","Apple"),("AVGO","Broadcom"),
 ("AMD","Advanced Micro Devices"),("CRM","Salesforce"),("ORCL","Oracle"),("ADBE","Adobe"),
 ("ACN","Accenture"),("CSCO","Cisco Systems"),("TXN","Texas Instruments"),("QCOM","Qualcomm"),
 ("INTU","Intuit"),("IBM","IBM"),("AMAT","Applied Materials"),("NOW","ServiceNow"),
 ("MU","Micron Technology"),("LRCX","Lam Research"),("ADI","Analog Devices"),("KLAC","KLA Corp"),
 ("PANW","Palo Alto Networks"),("SNPS","Synopsys"),("CDNS","Cadence Design"),("INTC","Intel"),
 ("ANET","Arista Networks"),("MSI","Motorola Solutions"),("ROP","Roper Technologies"),
 ("APH","Amphenol"),("NXPI","NXP Semiconductors"),("FTNT","Fortinet"),("MCHP","Microchip"),
 ("ON","ON Semiconductor"),("GLW","Corning"),("HPQ","HP Inc"),("DELL","Dell Technologies"),
 ("WDC","Western Digital"),("STX","Seagate"),("TER","Teradyne"),("SWKS","Skyworks"),
 ("KEYS","Keysight"),("CDW","CDW Corp"),("IT","Gartner"),("ANSS","Ansys"),
 ("TYL","Tyler Technologies"),("ZBRA","Zebra Technologies"),("JBL","Jabil"),
 ("HPE","HP Enterprise"),("NTAP","NetApp"),("TDY","Teledyne"),("PTC","PTC Inc"),
 ("FSLR","First Solar"),
],
"XLV": [
 ("LLY","Eli Lilly"),("UNH","UnitedHealth"),("JNJ","Johnson & Johnson"),("ABBV","AbbVie"),
 ("MRK","Merck"),("TMO","Thermo Fisher"),("ABT","Abbott Labs"),("ISRG","Intuitive Surgical"),
 ("AMGN","Amgen"),("DHR","Danaher"),("PFE","Pfizer"),("BSX","Boston Scientific"),
 ("VRTX","Vertex Pharmaceuticals"),("SYK","Stryker"),("BMY","Bristol-Myers Squibb"),
 ("GILD","Gilead Sciences"),("MDT","Medtronic"),("CI","Cigna"),("ELV","Elevance Health"),
 ("REGN","Regeneron"),("MCK","McKesson"),("CVS","CVS Health"),("ZTS","Zoetis"),
 ("BDX","Becton Dickinson"),("HCA","HCA Healthcare"),("EW","Edwards Lifesciences"),
 ("A","Agilent"),("IQV","IQVIA"),("IDXX","IDEXX Labs"),("GEHC","GE HealthCare"),
 ("CNC","Centene"),("MRNA","Moderna"),("DXCM","DexCom"),("RMD","ResMed"),
 ("WST","West Pharmaceutical"),("BIIB","Biogen"),("COR","Cencora"),("ZBH","Zimmer Biomet"),
 ("MTD","Mettler-Toledo"),("BAX","Baxter"),("HOLX","Hologic"),("VTRS","Viatris"),
 ("LH","Labcorp"),("DGX","Quest Diagnostics"),("STE","Steris"),("PODD","Insulet"),
 ("MOH","Molina Healthcare"),("CAH","Cardinal Health"),("CRL","Charles River Labs"),
],
"XLF": [
 ("BRK-B","Berkshire Hathaway"),("JPM","JPMorgan Chase"),("V","Visa"),("MA","Mastercard"),
 ("BAC","Bank of America"),("WFC","Wells Fargo"),("GS","Goldman Sachs"),("MS","Morgan Stanley"),
 ("SPGI","S&P Global"),("AXP","American Express"),("BLK","BlackRock"),("C","Citigroup"),
 ("PGR","Progressive"),("SCHW","Charles Schwab"),("CB","Chubb"),("MMC","Marsh & McLennan"),
 ("BX","Blackstone"),("FI","Fiserv"),("ICE","Intercontinental Exchange"),("CME","CME Group"),
 ("PYPL","PayPal"),("AON","Aon"),("USB","U.S. Bancorp"),("PNC","PNC Financial"),
 ("COF","Capital One"),("TFC","Truist Financial"),("AJG","Arthur J. Gallagher"),
 ("AIG","American International Group"),("MET","MetLife"),("TRV","Travelers"),("AFL","Aflac"),
 ("ALL","Allstate"),("PRU","Prudential Financial"),("BK","BNY Mellon"),("AMP","Ameriprise"),
 ("DFS","Discover Financial"),("MSCI","MSCI Inc"),("NDAQ","Nasdaq Inc"),("STT","State Street"),
 ("HIG","Hartford Financial"),("WTW","Willis Towers Watson"),("TROW","T. Rowe Price"),
 ("RJF","Raymond James"),("FITB","Fifth Third Bancorp"),("MTB","M&T Bank"),
 ("CINF","Cincinnati Financial"),("HBAN","Huntington Bancshares"),("RF","Regions Financial"),
 ("CFG","Citizens Financial"),("KEY","KeyCorp"),
],
"XLY": [
 ("AMZN","Amazon"),("TSLA","Tesla"),("HD","Home Depot"),("MCD","McDonald's"),
 ("BKNG","Booking Holdings"),("LOW","Lowe's"),("TJX","TJX Companies"),("SBUX","Starbucks"),
 ("NKE","Nike"),("ORLY","O'Reilly Automotive"),("CMG","Chipotle"),("ABNB","Airbnb"),
 ("MAR","Marriott"),("GM","General Motors"),("HLT","Hilton"),("AZO","AutoZone"),
 ("F","Ford Motor"),("ROST","Ross Stores"),("DHI","D.R. Horton"),("LEN","Lennar"),
 ("YUM","Yum! Brands"),("RCL","Royal Caribbean"),("EBAY","eBay"),("LVS","Las Vegas Sands"),
 ("TSCO","Tractor Supply"),("NVR","NVR Inc"),("PHM","PulteGroup"),("DECK","Deckers Outdoor"),
 ("EXPE","Expedia"),("CCL","Carnival"),("DRI","Darden Restaurants"),("ULTA","Ulta Beauty"),
 ("GRMN","Garmin"),("APTV","Aptiv"),("BBY","Best Buy"),("KMX","CarMax"),("POOL","Pool Corp"),
 ("WYNN","Wynn Resorts"),("MGM","MGM Resorts"),("LKQ","LKQ Corp"),
 ("NCLH","Norwegian Cruise Line"),("CZR","Caesars Entertainment"),("RL","Ralph Lauren"),
 ("TPR","Tapestry"),
],
"XLC": [
 ("META","Meta Platforms"),("GOOGL","Alphabet A"),("GOOG","Alphabet C"),("NFLX","Netflix"),
 ("DIS","Walt Disney"),("TMUS","T-Mobile US"),("CMCSA","Comcast"),("VZ","Verizon"),
 ("T","AT&T"),("CHTR","Charter Communications"),("EA","Electronic Arts"),
 ("TTWO","Take-Two Interactive"),("OMC","Omnicom"),("LYV","Live Nation"),
 ("WBD","Warner Bros. Discovery"),("IPG","Interpublic"),("NWSA","News Corp A"),
 ("FOXA","Fox Corp A"),("MTCH","Match Group"),
],
"XLI": [
 ("GE","GE Aerospace"),("CAT","Caterpillar"),("RTX","RTX Corp"),("UNP","Union Pacific"),
 ("HON","Honeywell"),("BA","Boeing"),("ETN","Eaton"),("LMT","Lockheed Martin"),
 ("DE","Deere & Co"),("UPS","United Parcel Service"),("ADP","Automatic Data Processing"),
 ("TT","Trane Technologies"),("PH","Parker Hannifin"),("GD","General Dynamics"),
 ("ITW","Illinois Tool Works"),("MMM","3M"),("EMR","Emerson Electric"),
 ("NOC","Northrop Grumman"),("CSX","CSX Corp"),("FDX","FedEx"),("NSC","Norfolk Southern"),
 ("WM","Waste Management"),("CTAS","Cintas"),("CARR","Carrier Global"),("PCAR","PACCAR"),
 ("JCI","Johnson Controls"),("GEV","GE Vernova"),("CMI","Cummins"),("PWR","Quanta Services"),
 ("URI","United Rentals"),("PAYX","Paychex"),("AME","Ametek"),("OTIS","Otis Worldwide"),
 ("RSG","Republic Services"),("FAST","Fastenal"),("LHX","L3Harris"),("VRSK","Verisk"),
 ("IR","Ingersoll Rand"),("EFX","Equifax"),("DAL","Delta Air Lines"),
 ("ODFL","Old Dominion Freight"),("HWM","Howmet Aerospace"),("AXON","Axon Enterprise"),
 ("XYL","Xylem"),("UAL","United Airlines"),("LUV","Southwest Airlines"),("DOV","Dover"),
 ("ROK","Rockwell Automation"),("WAB","Wabtec"),("BR","Broadridge"),
],
"XLP": [
 ("COST","Costco"),("WMT","Walmart"),("PG","Procter & Gamble"),("KO","Coca-Cola"),
 ("PEP","PepsiCo"),("PM","Philip Morris Intl"),("MO","Altria"),("MDLZ","Mondelez"),
 ("CL","Colgate-Palmolive"),("TGT","Target"),("KMB","Kimberly-Clark"),
 ("STZ","Constellation Brands"),("GIS","General Mills"),("SYY","Sysco"),("KVUE","Kenvue"),
 ("KDP","Keurig Dr Pepper"),("HSY","Hershey"),("KR","Kroger"),("ADM","Archer-Daniels-Midland"),
 ("MNST","Monster Beverage"),("DG","Dollar General"),("DLTR","Dollar Tree"),
 ("EL","Estee Lauder"),("CHD","Church & Dwight"),("MKC","McCormick"),("K","Kellanova"),
 ("CAG","Conagra Brands"),("TSN","Tyson Foods"),("HRL","Hormel Foods"),("SJM","J.M. Smucker"),
 ("CPB","Campbell's"),("LW","Lamb Weston"),("BG","Bunge Global"),("TAP","Molson Coors"),
 ("CLX","Clorox"),("BF-B","Brown-Forman B"),
],
"XLE": [
 ("XOM","Exxon Mobil"),("CVX","Chevron"),("COP","ConocoPhillips"),("EOG","EOG Resources"),
 ("WMB","Williams Companies"),("SLB","SLB"),("OKE","ONEOK"),("PSX","Phillips 66"),
 ("MPC","Marathon Petroleum"),("KMI","Kinder Morgan"),("VLO","Valero Energy"),
 ("OXY","Occidental Petroleum"),("BKR","Baker Hughes"),("HAL","Halliburton"),
 ("DVN","Devon Energy"),("FANG","Diamondback Energy"),("TRGP","Targa Resources"),
 ("CTRA","Coterra Energy"),("EQT","EQT Corp"),("APA","APA Corp"),("EXE","Expand Energy"),
],
"XLU": [
 ("NEE","NextEra Energy"),("SO","Southern Company"),("DUK","Duke Energy"),
 ("CEG","Constellation Energy"),("AEP","American Electric Power"),("SRE","Sempra"),
 ("D","Dominion Energy"),("PCG","PG&E Corp"),("EXC","Exelon"),("XEL","Xcel Energy"),
 ("ED","Consolidated Edison"),("PEG","Public Service Enterprise"),("VST","Vistra"),
 ("WEC","WEC Energy"),("EIX","Edison International"),("AWK","American Water Works"),
 ("DTE","DTE Energy"),("ETR","Entergy"),("AEE","Ameren"),("PPL","PPL Corp"),
 ("FE","FirstEnergy"),("CMS","CMS Energy"),("CNP","CenterPoint Energy"),("ATO","Atmos Energy"),
 ("NRG","NRG Energy"),("LNT","Alliant Energy"),("EVRG","Evergy"),("NI","NiSource"),
 ("ES","Eversource Energy"),("AES","AES Corp"),("PNW","Pinnacle West"),
],
"XLRE": [
 ("PLD","Prologis"),("AMT","American Tower"),("EQIX","Equinix"),("WELL","Welltower"),
 ("SPG","Simon Property"),("PSA","Public Storage"),("O","Realty Income"),
 ("DLR","Digital Realty"),("CCI","Crown Castle"),("CBRE","CBRE Group"),
 ("EXR","Extra Space Storage"),("VICI","VICI Properties"),("AVB","AvalonBay"),
 ("IRM","Iron Mountain"),("EQR","Equity Residential"),("SBAC","SBA Communications"),
 ("WY","Weyerhaeuser"),("INVH","Invitation Homes"),("MAA","Mid-America Apartment"),
 ("ESS","Essex Property"),("ARE","Alexandria Real Estate"),("DOC","Healthpeak"),
 ("KIM","Kimco Realty"),("UDR","UDR Inc"),("HST","Host Hotels"),("REG","Regency Centers"),
 ("CPT","Camden Property"),("BXP","BXP Inc"),("FRT","Federal Realty"),
],
"XLB": [
 ("LIN","Linde"),("SHW","Sherwin-Williams"),("APD","Air Products"),("ECL","Ecolab"),
 ("FCX","Freeport-McMoRan"),("NEM","Newmont"),("NUE","Nucor"),("DOW","Dow Inc"),
 ("DD","DuPont"),("PPG","PPG Industries"),("LYB","LyondellBasell"),("VMC","Vulcan Materials"),
 ("MLM","Martin Marietta"),("IFF","Intl Flavors & Fragrances"),("PKG","Packaging Corp"),
 ("AMCR","Amcor"),("STLD","Steel Dynamics"),("CF","CF Industries"),("BALL","Ball Corp"),
 ("IP","International Paper"),("ALB","Albemarle"),("EMN","Eastman Chemical"),
 ("CE","Celanese"),("MOS","Mosaic"),
],
}

TICKER_TO_ETF = {t: etf for etf, rows in CONSTITUENTS.items() for t, _ in rows}
TICKER_TO_NAME = {t: n for rows in CONSTITUENTS.values() for t, n in rows}
